"""Compatibility exports for the editable prompt catalog."""

from .prompt_catalog import (
    CONTROL_CONTRACT,
    CORE_SYSTEM_PROMPT,
    LINKED_PRIORITY_CONTRACT,
    OUTPUT_CONTRACT,
    PRIORITY_CONTRACT,
    TEXT_ONLY_PRIORITY_CONTRACT,
)

__all__ = [
    "CONTROL_CONTRACT", "CORE_SYSTEM_PROMPT", "LINKED_PRIORITY_CONTRACT",
    "OUTPUT_CONTRACT", "PRIORITY_CONTRACT", "TEXT_ONLY_PRIORITY_CONTRACT",
]
