// Shared semantic recipes. Styles live in the components layer of styles.css;
// local Tailwind utilities can safely refine spacing without fighting recipes.
export const ui = {
  input: "control input",
  select: "control select",
  panel: "panel",
  panelHeader: "panel-header",
  panelIcon: "panel-icon",
  panelHeading: "panel-heading",
  ideaPanel: "idea-panel",
  outputPanel: "output-panel",
  sidebar: "sidebar",
  sidebarBrand: "sidebar-brand",
  brandSub: "brand-sub",
  navCaption: "nav-caption",
  navItem: "nav-item",
  navCount: "nav-count",
  sidebarBottom: "sidebar-bottom",
  localLabel: "local-label",
  mainShell: "main-shell",
  topbar: "topbar",
  headerTitle: "header-title",
  connectionPill: "connection-pill",
  statusDot: "status-dot",
  localOnly: "local-only",
  main: "main-content",
  builderSave: "builder-save",
  pageHeading: "page-heading",
  eyebrow: "eyebrow",
  workspaceTag: "workspace-tag",
  workspaceGrid: "workspace-grid",
  column: "workspace-column",
  ideaInput: "control textarea idea-input",
  charCount: "char-count",
  inputHint: "input-hint",
  fields: "fields",
  threeFields: "three-fields",
  field: "field",
  selectWrap: "select-wrap",
  directorDescription: "director-description",
  resultStatus: "result-status",
  outputInput: "control textarea output-input",
  outputActions: "output-actions",
  button: "button",
  saveButton: "button button-save",
  primaryButton: "button button-primary",
  toggleRow: "toggle-row",
  toggleInput: "toggle-input",
  switch: "switch",
  toggleLabel: "toggle-label",
  countChip: "count-chip",
  imageSlot: "image-slot",
  uploadLabel: "upload-label",
  imageRemove: "image-remove",
  imageCaption: "image-caption",
  referenceMap: "reference-map",
  referenceRow: "reference-row",
  subtleNote: "subtle-note",
  notesInput: "control textarea notes-input",
  directorInput: "control textarea director-input",
  inlineActions: "inline-actions",
  settingsForm: "settings-form",
  textButton: "text-button",
  warningNote: "warning-note",
  generationBar: "generation-bar",
  generateButton: "generation-button generate-button",
  endButton: "generation-button end-button",
  belowActions: "below-actions",
  previewNote: "preview-note",
  message: "message",
  retryButton: "button retry-button",
  iconButton: "icon-button",
  deleteButton: "icon-button delete-button",
  toastRegion: "toast-region",
  toast: "toast",
  emptyState: "empty-state",
  emptyIcon: "empty-icon",
  savedCard: "panel saved-card",
  savedMeta: "saved-meta",
  dialog: "app-dialog save-dialog",
  directorsGrid: "directors-grid",
  directorList: "director-list",
  directorChoice: "director-choice list-choice",
  versionChoice: "list-choice",
  workflowStatus: "workflow-status",
  choiceCard: "choice-card",
  choiceChip: "choice-chip",
  promptText: "prompt-text",
};
